### ISSUE TITLE
Fail on complex array

### ISSUE THREAD

**Issue by talweksler** [0k/shyaml#23] opened 2016-06-14 15:48 UTC
It seems that if the yaml file contains a complex list like:
 package:
        ? - php5-mcrypt
          - php5-curl
          - php5-gd
          - php5-mysqlnd
          - locales
        : ensure: present

It will through an exception.

Wonder if there is an easy fix for it?

Thanks!

**Comment by vaab** [comment] 2016-06-14 16:14
Thank you for your report. May I ask you to quote properly your yaml content so I can reproduce your error. You could also provide the exact exception with full traceback. If you are using advanced YAML, you could also add a link to the http://yaml.org/ exact syntax reference you are using. If these instruction are too complex for you, please tell us what you would need to help you helping us.

**Comment by vaab** [comment] 2018-03-06 02:56
Closing this because the report is not clear enough for me here.
Feel free to reopen it if you can answer my question or clarify your problem.

**Closed by vaab** 2018-03-06 02:56 UTC
